"""empty message

Revision ID: e8e9b8aebbd0
Revises: 81891be32160
Create Date: 2022-04-07 22:01:29.060120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e9b8aebbd0'
down_revision = '81891be32160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ad_model_description', table_name='ad_model')
    op.create_index(op.f('ix_ad_model_description'), 'ad_model', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_model_description'), table_name='ad_model')
    op.create_index('ix_ad_model_description', 'ad_model', ['description'], unique=False)
    # ### end Alembic commands ###
