"""empty message

Revision ID: f27c2bc9049d
Revises: 
Create Date: 2022-04-07 21:50:10.863109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27c2bc9049d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_model_description'), 'ad_model', ['description'], unique=True)
    op.create_index(op.f('ix_ad_model_header'), 'ad_model', ['header'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_model_header'), table_name='ad_model')
    op.drop_index(op.f('ix_ad_model_description'), table_name='ad_model')
    op.drop_table('ad_model')
    # ### end Alembic commands ###
