"""empty message

Revision ID: f48a5e819f7f
Revises: f27c2bc9049d
Create Date: 2022-04-07 21:58:05.134282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48a5e819f7f'
down_revision = 'f27c2bc9049d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ad_model_header', table_name='ad_model')
    op.create_index(op.f('ix_ad_model_header'), 'ad_model', ['header'], unique=False)
    op.drop_column('ad_model', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_model', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_ad_model_header'), table_name='ad_model')
    op.create_index('ix_ad_model_header', 'ad_model', ['header'], unique=False)
    # ### end Alembic commands ###
